stopwords_list <- c(

    "ability",
    "able",
    # "academic",
    # "access",
    # "accuracy",
    # "achievement",
    # "acquisition",
    "across",
    "activity",
    # "addition",
    # "algebra",
    "also",
    "although",
    "among",
    "analysis",
    "analyzed",
    # "application",
    "approach",
    # "area",
    "article",
    # "assess",
    # "assessment",
    "based",
    # "basic",
    # "behavior",
    # "benefit",
    # "cai",
    # "calculator",
    "can",
    # "case",
    "child",
    "class",
    "classroom",
    "compared",
    "completed",
    # "computer",
    # "computer_based",
    # "concept",
    "condition",
    "conducted",
    "content",
    "control",
    "current",
    # "curriculum",
    "data",
    "demonstrate",
    "describe",
    "design",
    # "designed",
    "determine",
    # "develop",
    # "development",
    # "device",
    # "difference",
    # "different",
    # "difficulty",
    "disability",
    "discussed",
    "education",
    # "educational",
    "educator",
    "effect",
    "effective",
    # "environment",
    # "evaluate",
    # "evidence",
    "examine",
    # "experience",
    # "experimental",
    "explored",
    # "feedback",
    # "field",
    "find",
    "findings",
    "five",
    "four",
    # "fractions",
    # "functional_relation",
    "future",
    # "game",
    "general",
    "given",
    "grade",
    "group",
    "help",
    # "high",
    # "high_school",
    "however",
    "i.e",
    # "identify",
    # "impact",
    "implication",
    "important",
    "improve",
    "improved",
    "improvement",
    "include",
    "increase",
    "increased",
    # "independent",
    "indicate",
    "indicated",
    # "individual",
    # "information",
    "instruction",
    # "instructional",
    # "intellectual_disability",
    "intervention",
    "involve",
    # "knowledge",
    "learning",
    # "learning_disability",
    # "learning_disabled",
    # "level",
    "limitations",
    "limited",
    "literature",
    # "low",
    # "maintenance",
    # "manipulatives",
    "many",
    # "material",
    # "mathematical",
    "mathematics",
    # "mathematics_skill",
    "may",
    # "measure",
    "method",
    # "middle_school",
    #  "mld",
    # "model",
    # "multiple_probe",
    # "multiplication",
    # "need",
    # "new",
    # "non",
    # "number",
    "often",
    "one",
    # "online",
    # "order",
    "outcome",
    "overall",
    "paper",
    "participant",
    "participated",
    # "peer",
    "performance",
    # "positive",
    "posttest",
    # "potential",
    # "practice",
    "present",
    "pretest",
    "problem",
    # "problem_solving",
    # "program",
    "provide",
    "purpose",
    "reading",
    "regarding",
    # "related",
    "research",
    "researchers",
    # "resource",
    "result",
    "revealed",
    "review",
    "school",
    "science",
    # "score",
    # "secondary_student",
    # "session",
    "setting",
    "several",
    "show",
    "significant",
    "significantly",
    # "single_case",
    # "single_subject",
    "skill",
    # "social",
    # "software",
    # "solving",
    "special_education",
    # "specific",
    # "standard",
    #  "strategy",
    "student",
    "study",
    # "subject",
    # "subtraction",
    "suggest",
    "support",
    # "system",
    # "task",
    "teach",
    "teacher",
    "technology",
    # "term",
    # "testing",
    "three",
    # "time",
    # "tool",
    "traditional",
    # "training",
    "treatment",
    "two",
    # "type",
    #  "understanding",
    "use",
    # "variable",
    # "video",
    # "virtual_manipulatives",
    # "visual",
    "way",
    # "week",
    "well",
    "whether",
    "within",
    "without",
    # "word_problem",
    # "year",
    "yet"

)
